# Generated by Django 4.2.4 on 2023-08-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_canceled_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_current_period_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_current_period_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_ended_at',
        ),
    ]
