# Generated by Django 4.2.4 on 2023-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_remove_profile_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
