# Generated by Django 4.2.4 on 2023-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_profile_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_end_date',
        ),
    ]
